language: java

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
 