language: java

jdk:
  - oraclejdk7
# for now
#  - oraclejdk8

# script will call assemble
install: true

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assemble
  - ./gradlew check jacocoFullReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
 